### ISSUE TITLE
request

### ISSUE THREAD

**Issue by drtusharrasal** [JoshuaChou2018/MedAGI#1]

**Comment by drtusharrasal** [comment]
Can u provide the files Access through link to checkpoint files  'MedAGI  /skingpt_v4.2.pth',
              'MedAGI/weights/xray.pth',
              'MedAGI/weights/pathology.pth

**Comment by JoshuaChou2018** [comment]
Hi, thank you for your interest in our work. Please note:
- skingpt_v4.2.pth is the latest model from our previous work SkinGPT-4, which is not publically available currently, but you can go to https://github.com/JoshuaChou2018/SkinGPT-4 to download the early-stage model
- xray.pth, is the model for x-ray, the authors of XrayChat do not provide their model, so we trained the model ourselves, you can follow their [XrayChat](https://github.com/UCSD-AI4H/XrayChat) to train the model
- pathology.pth, is the model for pathology diagnosis, you can download the dataset from [https://github.com/masatsuneki/
332 histopathology-image-caption](https://github.com/masatsuneki/histopathology-image-caption) and train the model.

**Comment by viettham1998** [comment]
> * XrayChat

Hi @JoshuaChou2018, I would like to ask you about the xray.pth, currently repo [XrayChat](https://github.com/UCSD-AI4H/XrayChat) inaccessible, do you have another repo?

Also, can you give me information about [pretrained_medagi.pth](https://github.com/JoshuaChou2018/MedAGI/blob/49cb366aca8dd524dcc819b85b3125bad67a3d37/eval_configs/medagi_eval.yaml#L11C1-L11C82)? As I understand it, I need to set the path to this ckpt, but I don't see this file on your repo
